<<<<<<< refs/remotes/origin/Project_views
# Generated by Django 4.1.7 on 2023-05-08 04:52
=======
# Generated by Django 4.1.7 on 2023-05-11 21:48
>>>>>>> local

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Binnacle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binnacle_id', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('investment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('investorNum', models.IntegerField()),
                ('organization', models.TextField()),
                ('img', models.FileField(upload_to='pic/%y/')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.TextField(max_length=30)),
                ('icon_src', models.TextField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Convocatory',
            fields=[
                ('convocatory_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('closing_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=50)),
                ('project_description', models.TextField()),
                ('result', models.TextField()),
                ('scope', models.TextField()),
                ('work_plan', models.TextField()),
                ('budget', models.DecimalField(decimal_places=0, max_digits=10)),
                ('goal', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
                ('convocatory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.convocatory')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.state')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_id', models.CharField(max_length=10)),
                ('log_name', models.CharField(max_length=30)),
                ('date_time', models.DateTimeField()),
                ('observations', models.TextField()),
                ('results', models.TextField()),
                ('binnacle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.binnacle')),
            ],
        ),
        migrations.AddField(
            model_name='binnacle',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project'),
        ),
    ]
