# Generated by Django 4.1.7 on 2023-06-06 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 6, 8, 50, 49, 562719, tzinfo=datetime.timezone.utc)),
        ),
    ]
