# Generated by Django 4.1.7 on 2023-06-04 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('suggestion_id', models.AutoField(primary_key=True, serialize=False)),
                ('suggestion_name', models.CharField(max_length=50)),
                ('suggestion_description', models.TextField()),
                ('suggestion_work_plan', models.TextField()),
                ('suggestion_budget', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
    ]
