# Generated by Django 4.1.7 on 2023-03-30 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('investment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('investorNum', models.IntegerField()),
                ('organization', models.TextField()),
                ('img', models.FileField(upload_to='pic/%y/')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
