# Generated by Django 4.1.7 on 2023-06-06 03:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_beneficiary_user_alter_comments_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='email',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 6, 3, 17, 1, 992586, tzinfo=datetime.timezone.utc)),
        ),
    ]
