# Generated by Django 4.1.7 on 2023-04-03 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convocatory',
            name='projectId',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='role',
        ),
        migrations.RemoveField(
            model_name='log',
            name='binnacleId',
        ),
        migrations.RemoveField(
            model_name='project',
            name='nit',
        ),
        migrations.DeleteModel(
            name='Binnacle',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Convocatory',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Log',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
