# Generated by Django 4.1.7 on 2023-06-06 01:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_suggestion_comments_beneficiary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 6, 1, 55, 31, 259377, tzinfo=datetime.timezone.utc)),
        ),
    ]
