# Generated by Django 4.1.7 on 2023-06-06 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_comments_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 6, 9, 5, 47, 806956, tzinfo=datetime.timezone.utc)),
        ),
    ]
