# Generated by Django 4.1.7 on 2023-03-21 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Knowledge', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
