# Generated by Django 4.1.7 on 2023-06-03 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_employee_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='picture',
        ),
    ]
